# Generated by Django 3.1.5 on 2021-04-01 20:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('field_officer', '0001_initial'),
        ('county_manager', '0001_initial'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('theme', models.PositiveSmallIntegerField(choices=[(1, 'BUSINESS INCUBATION'), (2, 'AGRI-BUSINESS'), (3, 'WATER-SANITATION')], default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('agent', models.ManyToManyField(blank=True, null=True, related_name='projects', to='agents.Agent')),
                ('county_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='county_manager.countymanager')),
                ('field_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='field_officer.fieldofficer')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
