# Generated by Django 3.1.5 on 2021-04-12 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_area_division'),
        ('projects', '0002_auto_20210404_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_area', to='common.area'),
        ),
    ]
