# Generated by Django 3.1.5 on 2021-04-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='theme',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
