# Generated by Django 3.1.5 on 2021-04-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
