# Generated by Django 3.1.5 on 2021-04-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210416_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='theme',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, ''), (1, 'BUSINESS INCUBATION'), (2, 'AGRI-BUSINESS'), (3, 'WATER-SANITATION'), (4, 'HEALTH')], default=0, null=True),
        ),
    ]
