# Generated by Django 3.1.5 on 2021-05-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_initiated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='initiated_by',
            field=models.CharField(blank=True, choices=[('', ''), ('HQ', 'HQ'), ('COUNTY', 'COUNTY')], default='', max_length=10, null=True),
        ),
    ]
