# Generated by Django 3.1.5 on 2021-06-15 17:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_added',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
