# Generated by Django 3.1.5 on 2021-06-18 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_project_theme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectTheme',
        ),
        migrations.RemoveField(
            model_name='project',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='project',
            name='theme',
        ),
    ]
