# Generated by Django 3.1.5 on 2021-06-18 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_theme_color'),
        ('projects', '0020_project_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_theme', to='themes.theme'),
        ),
    ]
