# Generated by Django 3.1.5 on 2021-06-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20210624_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='delete_reason',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
