# Generated by Django 3.1.5 on 2021-06-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_project_delete_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
