# Generated by Django 3.1.5 on 2021-04-01 20:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('id_number', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('terms', models.PositiveSmallIntegerField(choices=[(1, 'PERMANENT-HQ'), (2, 'PERMANENT-COUNTY'), (3, 'CONTRACT')], default=3)),
                ('role', models.CharField(default='agent', max_length=200)),
                ('contract_approved_reason', models.TextField(blank=True, max_length=300, null=True)),
                ('permanent_approved_reason', models.TextField(blank=True, max_length=300, null=True)),
                ('contract_denied_reason', models.TextField(blank=True, max_length=300, null=True)),
                ('permanent_denied_reason', models.TextField(blank=True, max_length=300, null=True)),
                ('is_approved_by_field_officer_contract', models.BooleanField(default=False)),
                ('is_approved_by_county_manager_contract', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'agents',
            },
        ),
        migrations.CreateModel(
            name='AgentReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(blank=True, null=True, verbose_name='submission date')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('remarks', models.TextField(blank=True, max_length=2000, null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='agents.agent')),
            ],
            options={
                'verbose_name_plural': 'Agent Returns',
            },
        ),
    ]
