# Generated by Django 3.1.5 on 2021-04-01 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('agents', '0001_initial'),
        ('field_officer', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentreturn',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='projects.project'),
        ),
        migrations.AddField(
            model_name='agent',
            name='area',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_area', to='common.area'),
        ),
        migrations.AddField(
            model_name='agent',
            name='field_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='field_officer.fieldofficer'),
        ),
    ]
