# Generated by Django 3.1.5 on 2021-05-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_auto_20210403_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
