# Generated by Django 3.1.5 on 2021-06-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_auto_20210608_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='id_number',
            field=models.CharField(default='b2a60714-5341-43d1-855c-9a0aa9796f25', max_length=200, unique=True),
        ),
    ]
