# Generated by Django 3.1.5 on 2021-06-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_auto_20210615_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='id_number',
            field=models.CharField(default='2f67122c-01a3-4b4a-829c-f9fdd99e9244', max_length=200, unique=True),
        ),
    ]
