# Generated by Django 3.1.5 on 2021-06-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_auto_20210615_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='id_number',
            field=models.CharField(default='57b78d6f-dda9-4283-84f8-0fe3c3b3ed55', max_length=200, unique=True),
        ),
    ]
