# Generated by Django 3.1.5 on 2021-06-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_auto_20210615_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='id_number',
            field=models.CharField(default='09c567e5-43a9-4ec2-979a-0a39d552d362', max_length=200, unique=True),
        ),
    ]
