# Generated by Django 3.1.5 on 2021-06-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_auto_20210615_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='id_number',
            field=models.CharField(default='27e2c0f1-f56d-4d68-b760-0126347ddd1b', max_length=200, unique=True),
        ),
    ]
