# Generated by Django 3.1.5 on 2021-06-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_auto_20210615_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='id_number',
            field=models.CharField(default='ef3bf9ec-26bf-482d-b6da-28d870555acf', max_length=200, unique=True),
        ),
    ]
