# Generated by Django 3.1.5 on 2021-06-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0016_auto_20210618_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='id_number',
            field=models.CharField(default='50182cc7-0605-4b31-9cbe-1e7252f18672', max_length=200, unique=True),
        ),
    ]
