# Generated by Django 3.1.5 on 2021-06-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0017_auto_20210618_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='id_number',
            field=models.CharField(default='4f246bd4-6e2d-40fb-bff8-1388722e6d17', max_length=200, unique=True),
        ),
    ]
