# Generated by Django 3.1.5 on 2021-06-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0019_auto_20210618_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='delete_reason',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
