# Generated by Django 3.1.5 on 2021-06-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0020_agent_delete_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='approve_delete',
            field=models.BooleanField(default=False, help_text='Designates whether a request has been sent to delete this agent. Unselect this to show the request has been handled.'),
        ),
    ]
