# Generated by Django 3.1.5 on 2021-06-28 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents', '0022_agent_sender_of_delete_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_deleter', to=settings.AUTH_USER_MODEL),
        ),
    ]
