# Generated by Django 3.1.5 on 2021-05-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='staff number'),
        ),
    ]
