# Generated by Django 3.1.5 on 2021-05-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210513_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'CEO'), (3, 'Audit'), (4, 'Finace'), (5, 'Regional Manager'), (6, 'County Manager'), (7, 'Field Outreach Officer'), (8, 'Unassigned'), (9, 'Human Resource')], default=8, null=True),
        ),
    ]
