# Generated by Django 3.1.5 on 2022-04-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210513_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'CEO'), (3, 'Audit'), (4, 'Finance'), (5, 'Regional Manager'), (6, 'County Manager'), (7, 'Field Outreach Officer'), (8, 'Unassigned'), (9, 'Human Resource'), (10, 'Deputy Regional Manager'), (11, 'Deputy County Manager')], default=8, null=True),
        ),
    ]
