version: "3"

services:
  
  # proxy:
  #   image: nginx:alpine 
  #   container_name: ngeo_proxy
  #   restart: always
  #   tty: true
  #   volumes:
  #     - ../nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ../nginx/ssl/:/etc/ssl/
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   networks:
  #     - ngeo

  postgis:
    container_name: ngeo_db
    image: kartoza/postgis
    volumes:
      - "../ngeo-api/api/data/db:/var/lib/postgresql"
    environment:
      - POSTGRES_DB=ngeo_db_a
      - POSTGRES_USER=ngeo_db_a
      - POSTGRES_PASSWORD=ngeo_db_a
    ports:
      - "5432:5432"
    healthcheck:
      test: "exit 0"
    network_mode: host

  # api_ngeo:
  #   container_name: ngeo_api
  #   build:
  #     context: ../ngeo-api
  #     dockerfile: Dockerfile.api
  #   depends_on:
  #     - postgis
  #   environment:
  #     - NGEO_DATABASE_URL=postgis://ngeo_db_a:ngeo_db_a@192.168.60.109:5432/ngeo_db_b
  #   ports:
  #     - "8000:8000"
  #   network_mode: host

  
  geoserver:
    container_name: ngeo_geoserver
    build:
      context: ../geoserver
      dockerfile: Dockerfile.geoserver
    volumes:
      - "../geoserver:/geoserver"
    depends_on:
      - postgis
    environment:
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      - GEOSERVER_ADMIN_USER=admin
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - "8080:8080"
    restart: always
    network_mode: host
  

  mapserver:
    container_name: ngeo_mapserver
    image: klokantech/openmaptiles-server
    restart: always
    ports:
      - "7000:80"
    volumes:
      - ../mapserver/data:/data
    networks:
      - ngeo

  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:3.7
    restart: always
    volumes:
      - type: bind
        source: ../mapserver/data/kenya-latest.osm.pbf
        target: /nominatim/data.osm.pbf
    ports:
      - "9000:8080"
    environment:
      # see https://github.com/mediagis/nominatim-docker/tree/master/3.7#configuration for more options
      PBF_URL: https://download.geofabrik.de/africa/kenya-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/africa/kenya-updates/
    volumes:
      - nominatim-data:/var/lib/postgresql/12/main
    shm_size: 1gb

  frontend:
    container_name: ngeo_frontend
    build:
      context: ../ngeo-ui
      dockerfile: Dockerfile.frontend
    volumes:
      - "../ngeo-ui/src/config:/ngeo-ui/src/config"
      - type: bind
        source: ../ngeo-ui/src
        target: /ngeo-ui/src
    ports:
      - "3000:3000"
    network_mode: host

volumes:
  geoserver-data:
  nominatim-data:

networks:
  ngeo:
    driver: bridge
