version: "3.7"

services:
  db:
    container_name: ngeo_db
    image: kartoza/postgis:14
    volumes:
      - "./db:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=ngeo_db_a
      - POSTGRES_USER=ngeo_db_a
      - POSTGRES_PASSWORD=ngeo_db_a
    ports:
      - "5432:5432"
    healthcheck:
      test: "exit 0"

  geoserver:
    container_name: ngeo_geoserver
    build:
      context: ../geoserver
      dockerfile: Dockerfile.geoserver
    volumes:
      - "../geoserver:/geoserver"
    depends_on:
      - db
    environment:
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      - GEOSERVER_ADMIN_USER=admin
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - "8080:8080"
    restart: always

  mapserver:
    container_name: ngeo_mapserver
    image: klokantech/openmaptiles-server
    restart: always
    volumes:
      - "../mapserver/data:/data"
    ports:
      - "7000:80"

  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:3.7
    restart: always
    volumes:
      - "../mapserver/data/kenya-latest.osm.pbf:/nominatim/data.osm.pdf"
      - nominatim-data:/var/lib/postgresql/12/main
    ports:
      - "9000:8080"
    environment:
      # see https://github.com/mediagis/nominatim-docker/tree/master/3.7#configuration for more options
      PBF_URL: https://download.geofabrik.de/africa/kenya-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/africa/kenya-updates/
    shm_size: 1gb

  backend:
    container_name: ngeo_api
    build:
      context: ../ngeo-api
      dockerfile: Dockerfile.api
    volumes:
      - backend-static-data:/api/ngeo/staticfiles
    depends_on:
      - db
    environment:
      - NGEO_DATABASE_URL=postgis://ngeo_db_a:ngeo_db_a@db:5432/ngeo_db_a
    ports:
      - "8000:8000"

  frontend:
    container_name: ngeo_frontend
    build:
      context: ../ngeo-ui
      dockerfile: Dockerfile.frontend.prod
    volumes:
      - "../ngeo-ui/src/:/ngeo-ui/src/"
      - frontend-build-data:/ngeo-ui/build
    ports:
      - "3000:3000"

  nginx:
    image: nginx:1.21-alpine
    container_name: ngeo_nginx
    restart: always
    tty: true
    volumes:
      - "../nginx/ngeo.conf:/etc/nginx/conf.d/default.conf:ro"
      - frontend-build-data:/var/www/ngeo/build
      # - backend-static-data:/var/www/ngeo/static
    ports:
      - "80:8080"
      - "443:443"

volumes:
  frontend-build-data:
  backend-static-data:
  nominatim-data:
