# Generated by Django 3.1.5 on 2021-05-03 10:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('date_reported', models.DateTimeField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326)),
                ('origin', models.CharField(blank=True, max_length=250, null=True)),
                ('destination', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': ' Threats',
            },
        ),
    ]
