# Generated by Django 3.1.5 on 2021-05-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threat',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
