# Generated by Django 3.1.5 on 2021-05-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat', '0003_auto_20210506_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='threat',
            name='threat_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
