# Generated by Django 3.1.5 on 2021-04-01 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regional_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cm_area', to='common.area')),
                ('regional_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='county_managers', to='regional_manager.regionalmanager')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='county_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
