# Generated by Django 3.1.5 on 2022-04-28 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0002_area_division'),
        ('regional_manager', '0002_auto_20210704_1452'),
        ('county_manager', '0002_auto_20210704_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeputyCountyManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dcm_area', to='common.area')),
                ('regional_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputy_county_managers', to='regional_manager.regionalmanager')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputy_county_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
