# Generated by Django 3.1.5 on 2021-05-03 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidence', '0002_auto_20210503_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='title',
            new_name='name',
        ),
    ]
