# Generated by Django 2.2.16 on 2021-01-14 08:45

import os
from django.contrib.gis.utils import LayerMapping
from ngeo.apps.shapefiles.models import KenyaSubCounty

DATA_DIR_NAME = os.path.join("data", "ke_subcounty")

# Auto-generated `LayerMapping` dictionary for KenyaSubCounty model
kenyasubcounty_mapping = {
    'ctypcode': 'ctypcode',
    'county': 'county',
    'subcounty': 'subcounty',
    'geom': 'MULTIPOLYGON',
}
subcounty_shp = os.path.abspath(
    os.path.join(os.path.dirname(__file__), DATA_DIR_NAME, "ke_subcounty.shp")
)


def run(verbose=True):
    """
    This function used the LayerMapping import utility to
    load a shapefile to the database
    """
    # Takes model name, path to shapefile, mapping dict, encoding format
    lm = LayerMapping(
        KenyaSubCounty, subcounty_shp , kenyasubcounty_mapping, transform=False, encoding="iso-8859-1"
    )
    lm.save(strict=True, verbose=verbose)
