# Generated by Django 2.2.16 on 2021-01-14 08:45

import os
from django.contrib.gis.utils import LayerMapping
from ngeo.apps.shapefiles.models import County

DATA_DIR_NAME = os.path.join("data", "counties")

county_mapping = {
    "counties": "Counties",
    "codes": "Codes",
    "cty_code": "Cty_CODE",
    "dis": "dis",
    "geom": "MULTIPOLYGON",
}

county_shp = os.path.abspath(
    os.path.join(os.path.dirname(__file__), DATA_DIR_NAME, "counties.shp")
)


def run(verbose=True):
    """
    This function used the LayerMapping import utility to
    load a shapefile to the database
    """
    # Takes model name, path to shapefile, mapping dict, encoding format
    lm = LayerMapping(
        County, county_shp, county_mapping, transform=False, encoding="iso-8859-1"
    )
    lm.save(strict=True, verbose=verbose)
