# Generated by Django 2.2.16 on 2021-01-14 08:45

import os
from django.contrib.gis.utils import LayerMapping
from ngeo.apps.shapefiles.models import OutreachOfficer

DATA_DIR_NAME = os.path.join("data", "offices")

# Auto-generated `LayerMapping` dictionary for OutreachOfficer model
outreachofficer_mapping = {
    'tname': 'TName',
    'status': 'STATUS',
    'geom': 'MULTIPOINT',
}

office_shp = os.path.abspath(
    os.path.join(os.path.dirname(__file__), DATA_DIR_NAME, "Outreach_office.shp")
)


def run(verbose=True):
    """
    This function used the LayerMapping import utility to
    load a shapefile to the database
    """
    # Takes model name, path to shapefile, mapping dict, encoding format
    lm = LayerMapping(
        OutreachOfficer, office_shp, outreachofficer_mapping, transform=False, encoding="iso-8859-1"
    )
    lm.save(strict=True, verbose=verbose)
