# Generated by Django 3.1.5 on 2021-06-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='color',
            field=models.CharField(default='#00f', max_length=10),
        ),
    ]
